server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;
    error_page 404 /errors/404.php;
    
    location / {
        try_files $uri $uri/ =404;
    }
    
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    
    location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico)$ {
        try_files $uri =404;
    }
    
    location ~ /\.ht {
        deny all;
    }
}